### ISSUE TITLE
Spec would be helpful for the template generated projects

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-mvn-archetypes#1]
_From @sguptatw on March 31, 2016 8:58_

In the projects generated using web driver templates, an example spec would be helpful.
The default url to be pointed could be the gauge url.

_Copied from original issue: getgauge/Intellij-Plugin#127_

**Comment by apoorvam** [comment]
Fixed in this [commit](https://github.com/getgauge/gauge-mvn-archetypes/commit/25bf5265e9e020f57bac44f6d3eb2f8ee5953b88).
