### ISSUE TITLE
typo in gauge-java dependency version?

### ISSUE THREAD

**Issue by 7ravis** [getgauge/gauge-mvn-archetypes#24]
**gauge-archetype-java** and **gauge-archetype-selenium** both have extra characters in the gauge-java dependency version, making it invalid:
```
        <dependency>
            <groupId>com.thoughtworks.gauge</groupId>
            <artifactId>gauge-java</artifactId>
            <version>[0.6.8,)</version>
            <scope>test</scope>
        </dependency>
```

Removing the extra characters (`<version>0.6.8</version>`) is all that is needed to fix.

**Comment by sriv** [comment]
The `version` tag uses a range syntax as mentioned in the ['maven pom.xml syntax reference'](https://maven.apache.org/pom.html#Dependency_Version_Requirement_Specification)

Please, can you elaborate on where you see this being invalid?

**Comment by 7ravis** [comment]
I was just ignorant of that syntax. Thanks for your patience.
