### ISSUE TITLE
Update gauge-java version to 0.6.7

### ISSUE THREAD

**Issue by ajoecker** [getgauge/gauge-mvn-archetypes#9]
The current version in the pom.xml is `0.6.5`, which should be updated to the current latest version 0.6.7

**Comment by sguptatw** [comment]
The latest version of the archetypes 
`gauge-archetype-selenium` is `1.3.0`
`gauge-archetype-java` is `1.3.0`

These do not contain the changes. Hence the initialization using these archetypes are still creating projects with gauge-java `0.6.5`.

**Comment by BugDiver** [comment]
The fix should be available in Nightly >= May 11, 2018

**Comment by sguptatw** [comment]
Fixed in Archetype version 1.4.0
